name: brainS
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pyyaml
  - tqdm
  - ipython
  - jupyter
  - pillow
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - pip=20.*
  - pip:
    - scipy